theme = "catppuccin_frappe"

[editor]
line-number = "relative"
mouse = false
cursorline = true
continue-comments = true
true-color = true
bufferline = "multiple"
rulers = [100, 120]
color-modes = true
text-width = 100
trim-trailing-whitespace = true
end-of-line-diagnostics = "hint"


[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
g = { a = "code_action" } # Maps `ga` to show possible code actions
"space" = { "]" = ":bn", "[" = ":bp", "|"=":vs"}
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
"A-x" = "@x<A-d>" # Maps Alt-x to a macro selecting the whole line and deleting it without yanking it

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
